
services:
  chrome:
    build: .
    container_name: chrome_kiosk
    environment:
      - DISPLAY=:99
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    ports:
      - "5900:5900"  
    volumes:
      - /dev/shm:/dev/shm  
    restart: always
