
services:
  chrome-remote-desktop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chrome-remote-desktop
    environment:
      - VNC_PASSWORD=yourpassword  
    volumes:
      - ./home:/home/chrome
    ports:
      - "5900:5900"  # VNC
      - "3389:3389"  # RDP
    network_mode: bridge
    restart: always
