version: '3'
services:
  vnc:
    build: .
    container_name: vnc-container
    environment:
      - VNC_PASSWORD=123456  
    volumes:
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - "5900:5900"
      - "3389:3389"
    restart: always
